[package]
name = "flutter"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
gpui.workspace = true
ui.workspace = true
workspace.workspace = true
project.workspace = true
terminal_view.workspace = true
terminal.workspace = true
zed_actions.workspace = true
task.workspace = true
util.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
async-tungstenite = { workspace = true, features = ["tokio", "tokio-runtime"] }
futures.workspace = true
smol.workspace = true
url.workspace = true
regex.workspace = true
gpui_tokio.workspace = true
tokio.workspace = true
chrono.workspace = true
